lib/forge/config/routes.rb
Forge3::Application.routes.draw do
  devise_for :users, :controllers => { :sessions => "sessions" }
  devise_scope :user do
    get "/login" => "devise/sessions#new"
    get "/logout" => "sessions#destroy"
    get "/register" => "devise/registrations#new"
  end

  # SHOPPING & E-ECOMMERCE - FRONT END
  # ==================================

  # Order routes
  # ------------
  # new & create: not used, orders are created automatically when user commences shopping.
  # edit & update: refers to the contents of the order (the line items)
  # checkout: let's the user view their order, make any changes as needed before paying

  # Line item routes
  # ----------------
  # These belong to orders and are handled as additions or removals from orders, as such, they don't
  # really need all of the standard views and actions.
  resources :products, :only => [:index, :show] do
    collection do
      get :preview
    end
  end

  resources :addresses, :except => [:index, :show, :destroy]
  resources :orders, :only => [:update] do
    member do
      delete 'remove_from_cart'
      get 'paid'
    end
    collection do
      post 'add_to_cart'
      get 'cancel', 'get_cart'
    end
  end

  match 'orders/checkout' => 'orders#checkout_get', :via => :get
  match 'orders/checkout' => 'orders#checkout_post', :via => :post

  get "integrated_payment/billing"
  post "integrated_payment/pay"
  get "hosted_payment/billing"
  post "hosted_payment/notify"

  # END SHOPPING & E-ECOMMERCE - FRONT END
  # ======================================

  resources :countries, :only => [] do
    member do
      get 'get_provinces_for_checkout'
    end
  end

  resources :posts, :only => [:index, :show] do
    collection do
      get :preview, :feed
    end
    member do
      get :category
    end
  end
  resources :comments, :only => [:create, :destroy]
  #resources :galleries # we don't seem to have a galleries controller

  resources :events, :only => [:index, :show]

  if Forge.config.events.try(:display) == :calendar
    match 'events/:year/:month' => 'events#index', :via => :get
  end

  resources :dispatches, :only => [] do
    get 'read', 'unsubscribe', :on => :member
    resources :links, :controller => :dispatch_links, :only => [:show]
  end

  resources :contact, :only => :index do
    post     'submit', :on => :collection
  end

  namespace :forge do
    resources :pages do
      post    'reorder', :on => :collection
    end

    resources :posts
    resources :post_categories, :except => [:show, :new]
    resources :comments, :only => [:index, :destroy] do
     put     'approve', :on => :member
     put     'unapprove', :on => :member
    end

    resources :events, :except => [:show]

    resources :banners, :except => [:show] do
      post    'reorder', :on => :collection
    end

    resources :galleries, :except => [:show] do
      post    'reorder', :on => :collection
    end

    resources :assets do
      get 'drawer', :on => :collection
      get 'place', 'prepare', :on => :member
      post 'encode_notify', :on => :collection
    end

    resources :videos, :except => [:show] do
      get 'play', 'encode', :on => :member
      post 'encode_notify', :on => :collection
    end

    resources :video_feeds, :except => [:show, :destroy] do
      get 'publish', :on => :member
    end

    #########################
    #### eCommerce Stuff ####
    #########################
    resources :products, :except => [:show] do
      post 'reorder', :on => :collection
    end

    resources :product_categories, :except => [:show, :new] do
      post    'reorder', :on => :collection
    end

    resources :orders do
     put     'fulfill', :on => :member
     put     'unfulfill', :on => :member
    end

    resources :sales, :except => [:show] do
      get 'products', :on => :collection
    end

    resources :tax_rates, :except => [:show, :new]

    resources :countries, :only => [:index, :update] do
      member do
        get 'get_provinces'
      end
      collection do
        get 'get_active_countries'
      end
    end
    #############################
    #### End eCommerce Stuff ####
    #############################


    ############################
    #### Forge Press Stuff #####
    ############################
    resources :subscriber_groups, :except => [:show]
    resources :subscribers, :except => [:show] do
      get :export, :on => :collection
    end

    resources :dispatches do
     get :queue, :chart_data, :opens, :clicks, :unsubscribes, :on => :member
     put :test_send, :send_all, :on => :member
     resources :links, :controller => :dispatch_links, :only => [:index]
     resources :opens, :controller => :dispatch_opens, :only => [:index]
    end
    ############################
    ## End Forge Press Stuff ###
    ############################

    resources :users, :except => [:show] do
      get 'approve', :on => :member
    end

    resource :settings, :only => [:show, :update]

    #resources :help_topics, :only => [:index, :show]
    match "help", :controller => :help_topics, :action => :index
    match "help/search", :controller => :help_topics, :action => :search
    match "help/:slug", :controller => :help_topics, :action => :show

    root :to => "index#index"
  end

  #See how all your routes lay out with "rake routes"

  #This is a legacy wild controller route that's not recommended for RESTful applications.
  #Note: This route will make all actions in every controller accessible via GET requests.
  #match ':controller(/:action(/:id(.:format)))'

  match 'posts/:month/:year', :controller => 'posts', :action => 'index'
  match '/pages/preview', :controller => 'pages', :action => 'preview'
  match "/sitemap", :controller => 'index', :action => 'sitemap'
  match '*slugs', :controller => 'pages', :action => 'show'
  root :to => "index#index"
end

lib/forge/app/views/forge/shared/menu_items/_assets.html.haml
- if can?(:index, Asset)
  - item = "asset_library"
  = forge_menu_item item, forge_assets_path, :active => is_active("assets"), :submenu => false

lib/forge/app/views/forge/shared/menu_items/_banners.html.haml
- if can?(:index, Banner)
  = forge_menu_item item, forge_banners_path, :active => is_active("banners"), :submenu => can?(:create, Banner)
  - if can?(:create, Banner)
    %ul.forge_submenu{ :class => is_active(["banners"]) ? "#{item} active" : item }
      = link_to "New Banner", new_forge_banner_path, :class => ("active" if is_active(["banners"]) && params[:action] == "new")
    .spacer

lib/forge/app/views/forge/shared/menu_items/_comments.html.haml
- if can?(:index, Comment)
  = forge_menu_item "Comments", forge_comments_path, :active => is_active("comments"), :submenu => false

lib/forge/app/views/forge/shared/menu_items/_dispatches.html.haml
- if can?(:index, Dispatch)
  - item = "forge_press"
  = forge_menu_item item, forge_dispatches_path, :active => is_active(['dispatches', 'subscribers', 'subscriber_groups']), :submenu => true
  %ul.forge_submenu{ :class => is_active(['dispatches', 'subscribers', 'subscriber_groups']) ? "#{item} active" : item }
    = link_to "Dispatches", forge_dispatches_path, :class => ('active' if is_active('dispatches'))
    = link_to "Subscribers", forge_subscribers_path, :class => ('active' if is_active('subscribers')) if can?(:index, Subscriber)
    = link_to "Groups", forge_subscriber_groups_path, :class => ('active' if is_active('subscriber_groups')) if can?(:index, SubscriberGroup)

  .spacer

lib/forge/app/views/forge/shared/menu_items/_events.html.haml
- if can?(:index, Event)
  = forge_menu_item item, forge_events_path, :active => is_active("events"), :submenu => can?(:create, Event)
  - if can?(:create, Event)
    %ul.forge_submenu{ :class => is_active(["events"]) ? "#{item} active" : item }
      = link_to "New Event", new_forge_event_path, :class => ("active" if is_active(["events"]) && params[:action] == "new")
    .spacer

lib/forge/app/views/forge/shared/menu_items/_galleries.html.haml
- if can?(:index, Gallery)
  = forge_menu_item item, forge_galleries_path, :active => is_active("galleries"), :submenu => can?(:create, Gallery)
  - if can?(:create, Gallery)
    %ul.forge_submenu{ :class => is_active(["galleries"]) ? "#{item} active" : item }
      = link_to "New Gallery", new_forge_gallery_path, :class => ("active" if is_active(["galleries"]) && params[:action] == "new")
    .spacer

lib/forge/app/views/forge/shared/menu_items/_pages.html.haml
- if can?(:index, Page)
  = forge_menu_item item, forge_pages_path, :active => is_active("pages"), :submenu => can?(:create, Page)
  - if can?(:create, Page)
    %ul.forge_submenu{ :class => is_active(["pages"]) ? "#{item} active" : item }
      = link_to "New Page", new_forge_page_path, :class => ("active" if is_active(["pages"]) && params[:action] == "new")
    .spacer

lib/forge/app/views/forge/shared/menu_items/_posts.html.haml
- if can?(:index, Post)
  = forge_menu_item item, forge_posts_path, :active => is_active(["posts", "post_categories"]), :submenu => can?(:create, Post) || can?(:index, PostCategory)
  - if can?(:create, Post) || can?(:index, PostCategory)
    %ul.forge_submenu{ :class => is_active(["posts", "post_categories"]) ? "#{item} active" : item }
      = link_to "New Post", new_forge_post_path, :class => ("active" if params[:controller] == "forge/posts" && params[:action] == "new") if can?(:create, Post)
      = link_to "Post Categories", forge_post_categories_path, :class => ("active" if params[:controller] == "forge/post_categories") if can?(:index, PostCategory)
    .spacer

lib/forge/app/views/forge/shared/menu_items/_products.html.haml
- if can?(:index, Product)
  = forge_menu_item item, forge_products_path, :active => is_active(["products", "product_categories", "sales", "orders"]), :alt_title => "Shopping", :submenu => can?(:create, Product) || can?(:index, ProductCategory) || can?(:index, Order) || can?(:index, Sale)
  %ul.forge_submenu{ :class => is_active(["products", "product_categories", "orders", "sales"]) ? "#{item} active" : item }
    = link_to "New Product", new_forge_product_path, :class => ('active' if is_active('products') && params[:action] == "new") if can?(:create, Product)
    = link_to "Product Categories", forge_product_categories_path, :class => ('active' if is_active('product_categories')) if can?(:index, ProductCategory)
    = link_to "Orders", forge_orders_path, :class => ('active' if is_active('orders')) if can?(:index, Order)
    = link_to "Sales", forge_sales_path, :class => ('active' if is_active('sales')) if can?(:index, Sale)
  .spacer

lib/forge/app/views/forge/shared/menu_items/_settings.html.haml
- if can?(:index, MySettings)
  = forge_menu_item item, forge_settings_path, :active => is_active(["settings"])

lib/forge/app/views/forge/shared/menu_items/_subscribers.html.haml
- if can?(:index, Subscriber)
  - item = "subscribers"
  = forge_menu_item item, forge_subscribers_path, :active => is_active(['subscribers', 'subscriber_groups']), :submenu => true
  %ul.forge_submenu{ :class => is_active(['subscribers', 'subscriber_groups']) ? "#{item} active" : item }
    = link_to "Subscribers", forge_subscribers_path, :class => ('active' if is_active('subscribers')) if can?(:index, Subscriber)
    = link_to "Groups", forge_subscriber_groups_path, :class => ('active' if is_active('subscriber_groups')) if can?(:index, SubscriberGroup)

  .spacer

lib/forge/app/views/forge/shared/menu_items/_users.html.haml
- if can?(:index, User)
  = forge_menu_item item, forge_users_path, :active => is_active("users"), :submenu => false

lib/forge/app/views/forge/shared/menu_items/_video_feeds.html.haml
- if can?(:index, VideoFeed)
  = forge_menu_item item, forge_video_feeds_path, :active => is_active("video_feeds"), :alt_title => "Video Feed", :submenu => true
  %ul.forge_submenu{ :class => is_active(["video_feeds"]) ? "#{item} active" : item }
    = link_to "Pull Video Feed", new_forge_video_feed_path, :class => ("active" if is_active(["video_feeds"]) && params[:action] == "new"), :id => "pull-video-feed"
  .spacer

lib/forge/app/views/forge/shared/menu_items/_videos.html.haml
- if can?(:index, Video)
  = forge_menu_item item, forge_videos_path, :active => is_active("videos"), :submenu => can?(:create, Video)
  - if can?(:create, Video)
    %ul.forge_submenu{ :class => is_active(["videos"]) ? "#{item} active" : item }
      = link_to "New Video", new_forge_video_path, :class => ("active" if is_active(["videos"]) && params[:action] == "new")
    .spacer